# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				pufferfish = true
				dolphin = true
				item = true
				bee = true
				turtle = true
				zombie_villager = true
				cow = true
				tropical_fish = true
				pig = true
				slime = true
				skeleton = true
				bat = true
				zombie = true
				glow_squid = true
				cod = true
				witch = true
				glow_item_frame = false
				squid = true
				drowned = true
				spider = true
				creeper = true
				sheep = true
				player = true
				enderman = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true

			[light_sources.settings.entities.friendsandfoes]
				mauler = true

			[light_sources.settings.entities.creeperoverhaul]
				ocean_creeper = true
				cave_creeper = true
				savannah_creeper = true

