# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				bat = true
				rabbit = true
				polar_bear = true
				villager = true
				skeleton = true
				zombie = true
				creeper = true
				zombie_villager = true
				spider = true
				glow_squid = true
				stray = true
				pillager = true
				witch = true
				enderman = true
				slime = true
				pig = true
				squid = true
				cod = true
				chicken = true
				dolphin = true
				item = true
				armor_stand = true
				sheep = true
				pufferfish = true
				salmon = true
				drowned = true
				cow = true
				bee = true
				frog = true
				cat = true
				horse = true
				tnt_minecart = true
				chest_minecart = true
				axolotl = true
				tropical_fish = true
				mooshroom = true
				zombified_piglin = true
				ocelot = true
				panda = true
				vindicator = true
				parrot = true

			[light_sources.settings.entities.mythicmobs]
				drake = true
				kobold = true
				mushroom_thing = true
				kobold_warrior = true
				chupacabra = true

			[light_sources.settings.entities.wildlife]
				lark = true
				sparrow = true
				starfish = true
				clam = true
				horseshoecrab = true
				sanddollar = true
				seaurchin = true
				koi = true
				shrimp = true
				jellyfish = true
				prawn = true
				bettafish = true
				bluegill = true
				goldfish = true
				rainbow_trout = true
				catfish = true
				hedgehog = true
				ant = true
				june_beetle = true
				wren = true
				ladybug = true
				python = true
				glasswing_butterfly = true
				milk_snake = true
				gecko = true
				sunflowerbeetle = true
				white_eye = true
				king_snake = true
				monarch_butterfly = true
				grass_snake = true
				snail = true
				dragonfly = true
				tiger_butterfly = true
				cricket = true
				stickbug = true
				spicebush_butterfly = true
				spider = true
				beaver = true
				swallow = true
				alligator = true
				badger = true
				flycatcher = true
				hammerhead_shark = true

			[light_sources.settings.entities.graveyard]
				corrupted_pillager = true
				skeleton_creeper = true
				acolyte = true
				corrupted_vindicator = true
				nightmare = true

			[light_sources.settings.entities.variantsandventures]
				gelid = true
				thicket = true
				verdant = true

			[light_sources.settings.entities.creeperoverhaul]
				snowy_creeper = true
				cave_creeper = true
				hills_creeper = true
				dripstone_creeper = true
				bamboo_creeper = true
				jungle_creeper = true

			[light_sources.settings.entities.earthtojavamobs]
				piebald_pig = true
				gold_crested_chicken = true
				dairy_cow = true
				skeleton_wolf = true
				inky_sheep = true
				mottled_pig = true
				fancy_chicken = true
				fuzzy_sheep = true
				bold_striped_rabbit = true
				cream_cow = true
				muddy_pig = true
				skewbald_chicken = true
				spotted_pig = true
				muddy_foot_rabbit = true
				rainbow_sheep = true
				flecked_sheep = true
				jumbo_rabbit = true
				cookie_cow = true
				lobber_zombie = true

			[light_sources.settings.entities.meadow]
				wooly_cow = true

			[light_sources.settings.entities.adventurez]
				amethyst_golem = true

			[light_sources.settings.entities.endermanoverhaul]
				mushroom_fields_enderman = true
				cave_enderman = true

			[light_sources.settings.entities.friendsandfoes]
				rascal = true
				glare = true

			[light_sources.settings.entities.missingwilds]
				firefly_swarm = true

			[light_sources.settings.entities.fallingtrees]
				tree = true

