# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				pig = true
				parrot = true
				zombified_piglin = true
				allay = true
				pillager = true
				vindicator = true
				item = true
				cow = true
				glow_squid = true
				bat = true
				creeper = true
				zombie = true
				spider = true
				zombie_villager = true
				skeleton = true
				enderman = true
				axolotl = true
				sheep = true
				villager = true
				iron_golem = true
				witch = true
				bee = true
				chicken = true
				armor_stand = true
				squid = true
				cave_spider = true
				pufferfish = true
				salmon = true
				vex = true
				fox = true

			[light_sources.settings.entities.adventurez]
				amethyst_golem = true

			[light_sources.settings.entities.earthtojavamobs]
				freckled_rabbit = true
				cream_cow = true
				piebald_pig = true
				cookie_cow = true
				amber_chicken = true
				sooty_pig = true
				stormy_chicken = true
				bold_striped_rabbit = true
				skewbald_chicken = true
				skeleton_wolf = true
				pink_footed_pig = true
				flecked_sheep = true

			[light_sources.settings.entities.friendsandfoes]
				mauler = true

			[light_sources.settings.entities.wildlife]
				june_beetle = true
				ant = true
				glasswing_butterfly = true
				flycatcher = true
				bluebird = true
				sparrow = true
				tiger_butterfly = true
				grass_snake = true
				lark = true
				spider = true
				cricket = true
				rhino_beetle = true
				iguana = true
				monarch_butterfly = true
				dragonfly = true
				oriole = true
				alligator = true
				chameleon = true
				spicebush_butterfly = true
				deer = true
				boar = true
				staghorn_beetle = true
				possum = true
				hedgehog = true
				porcupine = true
				goldfinch = true
				towhee = true
				phoebe = true
				ferret = true
				badger = true

			[light_sources.settings.entities.variantsandventures]
				thicket = true
				verdant = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				cave_creeper = true
				jungle_creeper = true
				dark_oak_creeper = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				nightmare = true
				corrupted_pillager = true
				corrupted_vindicator = true
				acolyte = true

			[light_sources.settings.entities.mythicmobs]
				chupacabra = true
				mushroom_thing = true
				kobold = true
				kobold_warrior = true

